name: Build Status

# Step 1: Build on pull-requests or pushes to main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  # Step 2: Build Android sample
  build-java:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        regex:
        - "android"
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set commit range (push to the main branch, for example, merge)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV

      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV

      - name: Build
        run: .github/workflows/build/build.sh
        shell: bash
        env:
          COMMIT_RANGE: ${{ env.COMMIT_RANGE }}
          REGEX: ${{ matrix.regex }}

  # Step 3: Build iOS sample
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        regex:
        # copybara:strip_begin
        # LINT.IfChange
        # copybara:strip_end
        - "ios"
        # copybara:strip_begin
        # LINT.ThenChange(//depot/google3/googlemac/iPhone/InteractiveMediaAds/IMA/ios/samples/clientSide/copy.bara.sky)
        # copybara:strip_end
    steps:
      - name: Clone Repository
        uses: actions/checkout@v1

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Pod repo update
        run: pod repo update

      - name: Install xcpretty
        run: sudo gem install xcpretty

      - name: Set commit range (push to the main branch, for example, merge)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV

      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV

      - name: Build
        run: .github/workflows/build/ios_build.sh
        shell: bash
        env:
          COMMIT_RANGE: ${{ env.COMMIT_RANGE }}
          REGEX: ${{ matrix.regex }}